name: myenv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - boost-cpp=1.85.0=hfcd56d9_4
  - brotli=1.2.0=hf139dec_1
  - brotli-bin=1.2.0=h8616949_1
  - bzip2=1.0.8=h500dc9f_9
  - c-ares=1.34.6=hb5e19a0_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - contourpy=1.3.3=py313h98b818e_4
  - curl=8.18.0=h9a2545f_1
  - cycler=0.12.1=pyhcf101f3_2
  - fastp=1.1.0=h9ea9c2a_0
  - fonttools=4.61.1=py313h0f4d31d_0
  - freetype=2.14.1=h694c41f_0
  - icu=75.1=h120a0e1_0
  - isa-l=2.31.1=h6e16a3a_1
  - kiwisolver=1.4.9=py313ha1c5e85_2
  - krb5=1.22.2=h207b36a_0
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hcca01a6_1
  - libblas=3.11.0=5_he492b99_openblas
  - libboost=1.85.0=hcca3243_4
  - libboost-devel=1.85.0=h2b186f8_4
  - libboost-headers=1.85.0=h694c41f_4
  - libbrotlicommon=1.2.0=h8616949_1
  - libbrotlidec=1.2.0=h8616949_1
  - libbrotlienc=1.2.0=h8616949_1
  - libcblas=3.11.0=5_h9b27e0a_openblas
  - libcurl=8.18.0=h9a2545f_1
  - libcxx=21.1.8=h4fb565c_2
  - libdeflate=1.22=h00291cd_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libexpat=2.7.4=h991f03e_0
  - libffi=3.5.2=hd1f9c09_0
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - libgcc=15.2.0=h08519bb_18
  - libgff=2.0.0=h2ec61ea_3
  - libgfortran=15.2.0=h7e5c614_18
  - libgfortran5=15.2.0=hd16e46c_18
  - libhwloc=2.12.2=default_h273dbb7_1000
  - libiconv=1.18=h57a12c2_2
  - libjemalloc=5.3.0=hac325c4_1
  - libjpeg-turbo=3.1.2=h8616949_0
  - liblapack=3.11.0=5_h859234e_openblas
  - liblzma=5.8.2=h11316ed_0
  - liblzma-devel=5.8.2=h11316ed_0
  - libmpdec=4.0.0=hf3981d6_1
  - libnghttp2=1.67.0=h3338091_0
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libpng=1.6.55=h07817ec_0
  - libsqlite=3.51.2=hb99441e_0
  - libssh2=1.11.1=hed3591d_0
  - libtiff=4.7.0=hf4bdac2_2
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxml2=2.14.6=h7b7ecba_2
  - libxml2-16=2.14.6=ha1d9b0f_2
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.8=h472b3d1_0
  - matplotlib=3.10.8=py313habf4b1d_0
  - matplotlib-base=3.10.8=py313h4ad75b8_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncbi-vdb=3.3.0=h5fa12a8_0
  - ncurses=6.5=h0622a9a_3
  - numpy=2.4.2=py313hf1665ba_1
  - openjpeg=2.5.3=h036ada5_1
  - openssl=3.6.1=hb6871ef_1
  - packaging=26.0=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - perl=5.32.1=7_h10d778d_perl5
  - perl-alien-build=2.84=pl5321h18d8cf3_1
  - perl-alien-build-plugin-download-gitlab=0.01=pl5321hdfd78af_0
  - perl-alien-libxml2=0.20=pl5321h3e28226_0
  - perl-business-isbn=3.007=pl5321hd8ed1ab_0
  - perl-business-isbn-data=20210112.006=pl5321hd8ed1ab_0
  - perl-capture-tiny=0.48=pl5321h694c41f_1
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-ffi-checklib=0.28=pl5321hdfd78af_0
  - perl-file-chdir=0.1011=pl5321hd8ed1ab_0
  - perl-file-path=2.18=pl5321hd8ed1ab_0
  - perl-file-temp=0.2304=pl5321hd8ed1ab_0
  - perl-file-which=1.24=pl5321hd8ed1ab_0
  - perl-importer=0.026=pl5321hd8ed1ab_0
  - perl-parent=0.243=pl5321hd8ed1ab_0
  - perl-path-tiny=0.124=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321h6e16a3a_2
  - perl-scope-guard=0.21=pl5321hd8ed1ab_0
  - perl-sub-info=0.002=pl5321hd8ed1ab_0
  - perl-term-table=0.028=pl5321hdfd78af_0
  - perl-test-fatal=0.016=pl5321h694c41f_0
  - perl-test-warnings=0.031=pl5321h694c41f_0
  - perl-test2-suite=0.000163=pl5321hdfd78af_0
  - perl-try-tiny=0.31=pl5321h694c41f_0
  - perl-uri=5.34=pl5321h694c41f_0
  - perl-xml-libxml=2.0210=pl5321h3e28226_1
  - perl-xml-namespacesupport=1.12=pl5321hd8ed1ab_0
  - perl-xml-sax=1.02=pl5321hd8ed1ab_0
  - perl-xml-sax-base=1.09=pl5321hd8ed1ab_0
  - pillow=11.3.0=py313hcfd0557_3
  - pip=26.0.1=pyh145f28c_0
  - pthread-stubs=0.4=h00291cd_1002
  - pyparsing=3.3.2=pyhcf101f3_0
  - python=3.13.12=h894a449_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.13=8_cp313
  - qhull=2020.2=h3c5361c_5
  - readline=8.3=h68b038d_0
  - salmon=1.10.3=h23a0c69_5
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - six=1.17.0=pyhe01879c_1
  - sra-tools=3.2.1=h5fa12a8_1
  - staden_io_lib=1.15.1=h9f635df_0
  - statsmodels=0.14.6=py313h0f4b8c3_0
  - tbb=2022.3.0=h06b67a2_2
  - tk=8.6.13=h7142dee_3
  - tornado=6.5.3=py313hf050af9_0
  - xorg-libxau=1.0.12=h8616949_1
  - xorg-libxdmcp=1.1.5=h8616949_1
  - xz=5.8.2=h8df612c_0
  - xz-gpl-tools=5.8.2=h8df612c_0
  - xz-tools=5.8.2=h11316ed_0
  - zlib-ng=2.3.3=h8bce59a_1
  - zstd=1.5.7=h3eecb57_6
  - pip:
      - anndata==0.12.10
      - array-api-compat==1.13.0
      - donfig==0.8.1.post1
      - formulaic==1.2.1
      - formulaic-contrasts==1.0.0
      - google-crc32c==1.8.0
      - h5py==3.15.1
      - interface-meta==1.3.0
      - joblib==1.5.3
      - legacy-api-wrap==1.5
      - narwhals==2.16.0
      - natsort==8.4.0
      - numcodecs==0.16.5
      - pandas==2.3.3
      - pydeseq2==0.5.4
      - pytz==2025.2
      - pyyaml==6.0.3
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - session-info==1.0.1
      - stdlib-list==0.12.0
      - threadpoolctl==3.6.0
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - wrapt==2.1.1
      - zarr==3.1.5
prefix: /opt/anaconda3/envs/myenv
